version: v2

tasks:
  build-and-test:
    steps:
    - checkout
    - commands: 
      - pip install -r requirements.txt
      - pip install pytest-html
    - commands:
      - python test.py
      
    - reports/html: test-reports/*.html
    - reports/junit: test-reports/*.xml

    - coverage run test.py
    - coverage report && coverage html
    - reports/junit: test-reports/*.xml
    - reports/html: 
      dir: htmlcov
