version: v2

tasks:
  build-and-test:
    steps:
    - checkout
    - commands: 
      - pip install -r requirements.txt
      - pip install pytest-html
    - commands:
      - python test.py --html=report.html
      
    - reports/html:
        dir: coverage
        
    - reports/junit: test-reports/*.xml
