version: v2

tasks:
  build-and-test:
    steps:
    - checkout
    - commands: 
      - pip install -r requirements.txt
    - commands:
      - python test.py
    - reports/junit: test-reports/*.xml
